// AUTO-GENERATED by scripts/import-paradigms.ts — do not hand-edit. Rerun
// `pnpm import-paradigms` after vocab changes; put exceptions in paradigmReview.ts.
//
// Paradigms from Wiktionary (https://en.wiktionary.org), extracted by kaikki.org.
// Wiktionary content is licensed CC BY-SA 4.0.

import type { Case, GNumber } from './nouns';

export const PARADIGM_ATTRIBUTION =
  'Vocabulary-noun paradigms from Wiktionary via kaikki.org, CC BY-SA 4.0.';

export interface ImportedParadigm {
  forms: Record<GNumber, Record<Case, string>>;
  source: string;
  // Set when the import found something for Nae to confirm; kept out of drills.
  review?: string;
}

export const IMPORTED_PARADIGMS: Record<string, ImportedParadigm> = {
  "ch1-frāter": {
    "forms": {
      "sg": {
        "nom": "frāter",
        "gen": "frātris",
        "dat": "frātrī",
        "acc": "frātrem",
        "abl": "frātre"
      },
      "pl": {
        "nom": "frātrēs",
        "gen": "frātrum",
        "dat": "frātribus",
        "acc": "frātrēs",
        "abl": "frātribus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/f/fr/frater.jsonl"
  },
  "ch1-hōra": {
    "forms": {
      "sg": {
        "nom": "hōra",
        "gen": "hōrae",
        "dat": "hōrae",
        "acc": "hōram",
        "abl": "hōrā"
      },
      "pl": {
        "nom": "hōrae",
        "gen": "hōrārum",
        "dat": "hōrīs",
        "acc": "hōrās",
        "abl": "hōrīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/h/ho/hora.jsonl"
  },
  "ch1-īnsula": {
    "forms": {
      "sg": {
        "nom": "īnsula",
        "gen": "īnsulae",
        "dat": "īnsulae",
        "acc": "īnsulam",
        "abl": "īnsulā"
      },
      "pl": {
        "nom": "īnsulae",
        "gen": "īnsulārum",
        "dat": "īnsulīs",
        "acc": "īnsulās",
        "abl": "īnsulīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/i/in/insula.jsonl"
  },
  "ch1-pater": {
    "forms": {
      "sg": {
        "nom": "pater",
        "gen": "patris",
        "dat": "patrī",
        "acc": "patrem",
        "abl": "patre"
      },
      "pl": {
        "nom": "patrēs",
        "gen": "patrum",
        "dat": "patribus",
        "acc": "patrēs",
        "abl": "patribus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/p/pa/pater.jsonl"
  },
  "ch1-servus": {
    "forms": {
      "sg": {
        "nom": "servus",
        "gen": "servī",
        "dat": "servō",
        "acc": "servum",
        "abl": "servō"
      },
      "pl": {
        "nom": "servī",
        "gen": "servōrum",
        "dat": "servīs",
        "acc": "servōs",
        "abl": "servīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/s/se/servus.jsonl"
  },
  "ch1-turba": {
    "forms": {
      "sg": {
        "nom": "turba",
        "gen": "turbae",
        "dat": "turbae",
        "acc": "turbam",
        "abl": "turbā"
      },
      "pl": {
        "nom": "turbae",
        "gen": "turbārum",
        "dat": "turbīs",
        "acc": "turbās",
        "abl": "turbīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/t/tu/turba.jsonl"
  },
  "ch1-via": {
    "forms": {
      "sg": {
        "nom": "via",
        "gen": "viae",
        "dat": "viae",
        "acc": "viam",
        "abl": "viā"
      },
      "pl": {
        "nom": "viae",
        "gen": "viārum",
        "dat": "viīs",
        "acc": "viās",
        "abl": "viīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/v/vi/via.jsonl"
  },
  "ch2-cibus": {
    "forms": {
      "sg": {
        "nom": "cibus",
        "gen": "cibī",
        "dat": "cibō",
        "acc": "cibum",
        "abl": "cibō"
      },
      "pl": {
        "nom": "cibī",
        "gen": "cibōrum",
        "dat": "cibīs",
        "acc": "cibōs",
        "abl": "cibīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/c/ci/cibus.jsonl"
  },
  "ch2-fīlia": {
    "forms": {
      "sg": {
        "nom": "fīlia",
        "gen": "fīliae",
        "dat": "fīliae",
        "acc": "fīliam",
        "abl": "fīliā"
      },
      "pl": {
        "nom": "fīliae",
        "gen": "fīliārum",
        "dat": "fīliīs",
        "acc": "fīliās",
        "abl": "fīliīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/f/fi/filia.jsonl"
  },
  "ch2-fīlius": {
    "forms": {
      "sg": {
        "nom": "fīlius",
        "gen": "fīliī",
        "dat": "fīliō",
        "acc": "fīlium",
        "abl": "fīliō"
      },
      "pl": {
        "nom": "fīliī",
        "gen": "fīliōrum",
        "dat": "fīliīs",
        "acc": "fīliōs",
        "abl": "fīliīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/f/fi/filius.jsonl"
  },
  "ch2-forum": {
    "forms": {
      "sg": {
        "nom": "forum",
        "gen": "forī",
        "dat": "forō",
        "acc": "forum",
        "abl": "forō"
      },
      "pl": {
        "nom": "fora",
        "gen": "forōrum",
        "dat": "forīs",
        "acc": "fora",
        "abl": "forīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/f/fo/forum.jsonl"
  },
  "ch2-pecūnia": {
    "forms": {
      "sg": {
        "nom": "pecūnia",
        "gen": "pecūniae",
        "dat": "pecūniae",
        "acc": "pecūniam",
        "abl": "pecūniā"
      },
      "pl": {
        "nom": "pecūniae",
        "gen": "pecūniārum",
        "dat": "pecūniīs",
        "acc": "pecūniās",
        "abl": "pecūniīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/p/pe/pecunia.jsonl"
  },
  "ch2-vīnum": {
    "forms": {
      "sg": {
        "nom": "vīnum",
        "gen": "vīnī",
        "dat": "vīnō",
        "acc": "vīnum",
        "abl": "vīnō"
      },
      "pl": {
        "nom": "vīna",
        "gen": "vīnōrum",
        "dat": "vīnīs",
        "acc": "vīna",
        "abl": "vīnīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/v/vi/vinum.jsonl"
  },
  "ch3-amīcus": {
    "forms": {
      "sg": {
        "nom": "amīcus",
        "gen": "amīcī",
        "dat": "amīcō",
        "acc": "amīcum",
        "abl": "amīcō"
      },
      "pl": {
        "nom": "amīcī",
        "gen": "amīcōrum",
        "dat": "amīcīs",
        "acc": "amīcōs",
        "abl": "amīcīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/a/am/amicus.jsonl"
  },
  "ch3-ancilla": {
    "forms": {
      "sg": {
        "nom": "ancilla",
        "gen": "ancillae",
        "dat": "ancillae",
        "acc": "ancillam",
        "abl": "ancillā"
      },
      "pl": {
        "nom": "ancillae",
        "gen": "ancillārum",
        "dat": "ancillīs",
        "acc": "ancillās",
        "abl": "ancillīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/a/an/ancilla.jsonl"
  },
  "ch3-clāmor": {
    "forms": {
      "sg": {
        "nom": "clāmor",
        "gen": "clāmōris",
        "dat": "clāmōrī",
        "acc": "clāmōrem",
        "abl": "clāmōre"
      },
      "pl": {
        "nom": "clāmōrēs",
        "gen": "clāmōrum",
        "dat": "clāmōribus",
        "acc": "clāmōrēs",
        "abl": "clāmōribus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/c/cl/clamor.jsonl"
  },
  "ch3-equus": {
    "forms": {
      "sg": {
        "nom": "equus",
        "gen": "equī",
        "dat": "equō",
        "acc": "equum",
        "abl": "equō"
      },
      "pl": {
        "nom": "equī",
        "gen": "equōrum",
        "dat": "equīs",
        "acc": "equōs",
        "abl": "equīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/e/eq/equus.jsonl"
  },
  "ch3-gladius": {
    "forms": {
      "sg": {
        "nom": "gladius",
        "gen": "gladiī",
        "dat": "gladiō",
        "acc": "gladium",
        "abl": "gladiō"
      },
      "pl": {
        "nom": "gladiī",
        "gen": "gladiōrum",
        "dat": "gladiīs",
        "acc": "gladiōs",
        "abl": "gladiīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/g/gl/gladius.jsonl"
  },
  "ch3-senātor": {
    "forms": {
      "sg": {
        "nom": "senātor",
        "gen": "senātōris",
        "dat": "senātōrī",
        "acc": "senātōrem",
        "abl": "senātōre"
      },
      "pl": {
        "nom": "senātōrēs",
        "gen": "senātōrum",
        "dat": "senātōribus",
        "acc": "senātōrēs",
        "abl": "senātōribus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/s/se/senator.jsonl"
  },
  "ch3-urbs": {
    "forms": {
      "sg": {
        "nom": "urbs",
        "gen": "urbis",
        "dat": "urbī",
        "acc": "urbem",
        "abl": "urbe"
      },
      "pl": {
        "nom": "urbēs",
        "gen": "urbium",
        "dat": "urbibus",
        "acc": "urbēs",
        "abl": "urbibus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/u/ur/urbs.jsonl"
  },
  "ch4-deus": {
    "forms": {
      "sg": {
        "nom": "deus",
        "gen": "deī",
        "dat": "deō",
        "acc": "deum",
        "abl": "deō"
      },
      "pl": {
        "nom": "dī",
        "gen": "deōrum",
        "dat": "dīs",
        "acc": "deōs",
        "abl": "dīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/d/de/deus.jsonl"
  },
  "ch4-dominus": {
    "forms": {
      "sg": {
        "nom": "dominus",
        "gen": "dominī",
        "dat": "dominō",
        "acc": "dominum",
        "abl": "dominō"
      },
      "pl": {
        "nom": "dominī",
        "gen": "dominōrum",
        "dat": "dominīs",
        "acc": "dominōs",
        "abl": "dominīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/d/do/dominus.jsonl"
  },
  "ch4-dōnum": {
    "forms": {
      "sg": {
        "nom": "dōnum",
        "gen": "dōnī",
        "dat": "dōnō",
        "acc": "dōnum",
        "abl": "dōnō"
      },
      "pl": {
        "nom": "dōna",
        "gen": "dōnōrum",
        "dat": "dōnīs",
        "acc": "dōna",
        "abl": "dōnīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/d/do/donum.jsonl"
  },
  "ch4-perīculum": {
    "forms": {
      "sg": {
        "nom": "perīculum",
        "gen": "perīculī",
        "dat": "perīculō",
        "acc": "perīculum",
        "abl": "perīculō"
      },
      "pl": {
        "nom": "perīcula",
        "gen": "perīculōrum",
        "dat": "perīculīs",
        "acc": "perīcula",
        "abl": "perīculīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/p/pe/periculum.jsonl"
  },
  "ch4-puella": {
    "forms": {
      "sg": {
        "nom": "puella",
        "gen": "puellae",
        "dat": "puellae",
        "acc": "puellam",
        "abl": "puellā"
      },
      "pl": {
        "nom": "puellae",
        "gen": "puellārum",
        "dat": "puellīs",
        "acc": "puellās",
        "abl": "puellīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/p/pu/puella.jsonl"
  },
  "ch4-rēx": {
    "forms": {
      "sg": {
        "nom": "rēx",
        "gen": "rēgis",
        "dat": "rēgī",
        "acc": "rēgem",
        "abl": "rēge"
      },
      "pl": {
        "nom": "rēgēs",
        "gen": "rēgum",
        "dat": "rēgibus",
        "acc": "rēgēs",
        "abl": "rēgibus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/r/re/rex.jsonl"
  },
  "ch4-templum": {
    "forms": {
      "sg": {
        "nom": "templum",
        "gen": "templī",
        "dat": "templō",
        "acc": "templum",
        "abl": "templō"
      },
      "pl": {
        "nom": "templa",
        "gen": "templōrum",
        "dat": "templīs",
        "acc": "templa",
        "abl": "templīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/t/te/templum.jsonl"
  },
  "ch5-aqua": {
    "forms": {
      "sg": {
        "nom": "aqua",
        "gen": "aquae",
        "dat": "aquae",
        "acc": "aquam",
        "abl": "aquā"
      },
      "pl": {
        "nom": "aquae",
        "gen": "aquārum",
        "dat": "aquīs",
        "acc": "aquās",
        "abl": "aquīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/a/aq/aqua.jsonl"
  },
  "ch5-custōs": {
    "forms": {
      "sg": {
        "nom": "custōs",
        "gen": "custōdis",
        "dat": "custōdī",
        "acc": "custōdem",
        "abl": "custōde"
      },
      "pl": {
        "nom": "custōdēs",
        "gen": "custōdum",
        "dat": "custōdibus",
        "acc": "custōdēs",
        "abl": "custōdibus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/c/cu/custos.jsonl"
  },
  "ch5-iuvenis": {
    "forms": {
      "sg": {
        "nom": "iuvenis",
        "gen": "iuvenis",
        "dat": "iuvenī",
        "acc": "iuvenem",
        "abl": "iuvene"
      },
      "pl": {
        "nom": "iuvenēs",
        "gen": "iuvenum",
        "dat": "iuvenibus",
        "acc": "iuvenēs",
        "abl": "iuvenibus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/i/iu/iuvenis.jsonl"
  },
  "ch5-nox": {
    "forms": {
      "sg": {
        "nom": "nox",
        "gen": "noctis",
        "dat": "noctī",
        "acc": "noctem",
        "abl": "nocte"
      },
      "pl": {
        "nom": "noctēs",
        "gen": "noctium",
        "dat": "noctibus",
        "acc": "noctēs",
        "abl": "noctibus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/n/no/nox.jsonl"
  },
  "ch6-diēs": {
    "forms": {
      "sg": {
        "nom": "diēs",
        "gen": "diēī",
        "dat": "diēī",
        "acc": "diem",
        "abl": "diē"
      },
      "pl": {
        "nom": "diēs",
        "gen": "diērum",
        "dat": "diēbus",
        "acc": "diēs",
        "abl": "diēbus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/d/di/dies.jsonl"
  },
  "ch6-marītus": {
    "forms": {
      "sg": {
        "nom": "marītus",
        "gen": "marītī",
        "dat": "marītō",
        "acc": "marītum",
        "abl": "marītō"
      },
      "pl": {
        "nom": "marītī",
        "gen": "marītōrum",
        "dat": "marītīs",
        "acc": "marītōs",
        "abl": "marītīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/m/ma/maritus.jsonl"
  },
  "ch6-māter": {
    "forms": {
      "sg": {
        "nom": "māter",
        "gen": "mātris",
        "dat": "mātrī",
        "acc": "mātrem",
        "abl": "mātre"
      },
      "pl": {
        "nom": "mātrēs",
        "gen": "mātrum",
        "dat": "mātribus",
        "acc": "mātrēs",
        "abl": "mātribus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/m/ma/mater.jsonl"
  },
  "ch6-uxor": {
    "forms": {
      "sg": {
        "nom": "uxor",
        "gen": "uxōris",
        "dat": "uxōrī",
        "acc": "uxōrem",
        "abl": "uxōre"
      },
      "pl": {
        "nom": "uxōrēs",
        "gen": "uxōrum",
        "dat": "uxōribus",
        "acc": "uxōrēs",
        "abl": "uxōribus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/u/ux/uxor.jsonl"
  }
};
