// AUTO-GENERATED by scripts/import-paradigms.ts — do not hand-edit. Rerun
// `pnpm import-paradigms` after vocab changes; put exceptions in paradigmReview.ts.
//
// Paradigms from Wiktionary (https://en.wiktionary.org), extracted by kaikki.org.
// Wiktionary content is licensed CC BY-SA 4.0.

import type { Case, GNumber } from './nouns';

export const PARADIGM_ATTRIBUTION =
  'Vocabulary-noun paradigms from Wiktionary via kaikki.org, CC BY-SA 4.0.';

export interface ImportedParadigm {
  forms: Record<GNumber, Record<Case, string>>;
  source: string;
  // Set when the import found something for Nae to confirm; kept out of drills.
  review?: string;
}

export const IMPORTED_PARADIGMS: Record<string, ImportedParadigm> = {
  "ch1-frāter": {
    "forms": {
      "sg": {
        "nom": "frāter",
        "gen": "frātris",
        "dat": "frātrī",
        "acc": "frātrem",
        "abl": "frātre"
      },
      "pl": {
        "nom": "frātrēs",
        "gen": "frātrum",
        "dat": "frātribus",
        "acc": "frātrēs",
        "abl": "frātribus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/f/fr/frater.jsonl"
  },
  "ch1-hōra": {
    "forms": {
      "sg": {
        "nom": "hōra",
        "gen": "hōrae",
        "dat": "hōrae",
        "acc": "hōram",
        "abl": "hōrā"
      },
      "pl": {
        "nom": "hōrae",
        "gen": "hōrārum",
        "dat": "hōrīs",
        "acc": "hōrās",
        "abl": "hōrīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/h/ho/hora.jsonl"
  },
  "ch1-īnsula": {
    "forms": {
      "sg": {
        "nom": "īnsula",
        "gen": "īnsulae",
        "dat": "īnsulae",
        "acc": "īnsulam",
        "abl": "īnsulā"
      },
      "pl": {
        "nom": "īnsulae",
        "gen": "īnsulārum",
        "dat": "īnsulīs",
        "acc": "īnsulās",
        "abl": "īnsulīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/i/in/insula.jsonl"
  },
  "ch1-pater": {
    "forms": {
      "sg": {
        "nom": "pater",
        "gen": "patris",
        "dat": "patrī",
        "acc": "patrem",
        "abl": "patre"
      },
      "pl": {
        "nom": "patrēs",
        "gen": "patrum",
        "dat": "patribus",
        "acc": "patrēs",
        "abl": "patribus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/p/pa/pater.jsonl"
  },
  "ch1-servus": {
    "forms": {
      "sg": {
        "nom": "servus",
        "gen": "servī",
        "dat": "servō",
        "acc": "servum",
        "abl": "servō"
      },
      "pl": {
        "nom": "servī",
        "gen": "servōrum",
        "dat": "servīs",
        "acc": "servōs",
        "abl": "servīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/s/se/servus.jsonl"
  },
  "ch1-turba": {
    "forms": {
      "sg": {
        "nom": "turba",
        "gen": "turbae",
        "dat": "turbae",
        "acc": "turbam",
        "abl": "turbā"
      },
      "pl": {
        "nom": "turbae",
        "gen": "turbārum",
        "dat": "turbīs",
        "acc": "turbās",
        "abl": "turbīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/t/tu/turba.jsonl"
  },
  "ch1-via": {
    "forms": {
      "sg": {
        "nom": "via",
        "gen": "viae",
        "dat": "viae",
        "acc": "viam",
        "abl": "viā"
      },
      "pl": {
        "nom": "viae",
        "gen": "viārum",
        "dat": "viīs",
        "acc": "viās",
        "abl": "viīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/v/vi/via.jsonl"
  },
  "ch2-cibus": {
    "forms": {
      "sg": {
        "nom": "cibus",
        "gen": "cibī",
        "dat": "cibō",
        "acc": "cibum",
        "abl": "cibō"
      },
      "pl": {
        "nom": "cibī",
        "gen": "cibōrum",
        "dat": "cibīs",
        "acc": "cibōs",
        "abl": "cibīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/c/ci/cibus.jsonl"
  },
  "ch2-fīlia": {
    "forms": {
      "sg": {
        "nom": "fīlia",
        "gen": "fīliae",
        "dat": "fīliae",
        "acc": "fīliam",
        "abl": "fīliā"
      },
      "pl": {
        "nom": "fīliae",
        "gen": "fīliārum",
        "dat": "fīliīs",
        "acc": "fīliās",
        "abl": "fīliīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/f/fi/filia.jsonl"
  },
  "ch2-fīlius": {
    "forms": {
      "sg": {
        "nom": "fīlius",
        "gen": "fīliī",
        "dat": "fīliō",
        "acc": "fīlium",
        "abl": "fīliō"
      },
      "pl": {
        "nom": "fīliī",
        "gen": "fīliōrum",
        "dat": "fīliīs",
        "acc": "fīliōs",
        "abl": "fīliīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/f/fi/filius.jsonl"
  },
  "ch2-forum": {
    "forms": {
      "sg": {
        "nom": "forum",
        "gen": "forī",
        "dat": "forō",
        "acc": "forum",
        "abl": "forō"
      },
      "pl": {
        "nom": "fora",
        "gen": "forōrum",
        "dat": "forīs",
        "acc": "fora",
        "abl": "forīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/f/fo/forum.jsonl"
  },
  "ch2-pecūnia": {
    "forms": {
      "sg": {
        "nom": "pecūnia",
        "gen": "pecūniae",
        "dat": "pecūniae",
        "acc": "pecūniam",
        "abl": "pecūniā"
      },
      "pl": {
        "nom": "pecūniae",
        "gen": "pecūniārum",
        "dat": "pecūniīs",
        "acc": "pecūniās",
        "abl": "pecūniīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/p/pe/pecunia.jsonl"
  },
  "ch2-vīnum": {
    "forms": {
      "sg": {
        "nom": "vīnum",
        "gen": "vīnī",
        "dat": "vīnō",
        "acc": "vīnum",
        "abl": "vīnō"
      },
      "pl": {
        "nom": "vīna",
        "gen": "vīnōrum",
        "dat": "vīnīs",
        "acc": "vīna",
        "abl": "vīnīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/v/vi/vinum.jsonl"
  },
  "ch3-amīcus": {
    "forms": {
      "sg": {
        "nom": "amīcus",
        "gen": "amīcī",
        "dat": "amīcō",
        "acc": "amīcum",
        "abl": "amīcō"
      },
      "pl": {
        "nom": "amīcī",
        "gen": "amīcōrum",
        "dat": "amīcīs",
        "acc": "amīcōs",
        "abl": "amīcīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/a/am/amicus.jsonl"
  },
  "ch3-ancilla": {
    "forms": {
      "sg": {
        "nom": "ancilla",
        "gen": "ancillae",
        "dat": "ancillae",
        "acc": "ancillam",
        "abl": "ancillā"
      },
      "pl": {
        "nom": "ancillae",
        "gen": "ancillārum",
        "dat": "ancillīs",
        "acc": "ancillās",
        "abl": "ancillīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/a/an/ancilla.jsonl"
  },
  "ch3-clāmor": {
    "forms": {
      "sg": {
        "nom": "clāmor",
        "gen": "clāmōris",
        "dat": "clāmōrī",
        "acc": "clāmōrem",
        "abl": "clāmōre"
      },
      "pl": {
        "nom": "clāmōrēs",
        "gen": "clāmōrum",
        "dat": "clāmōribus",
        "acc": "clāmōrēs",
        "abl": "clāmōribus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/c/cl/clamor.jsonl"
  },
  "ch3-equus": {
    "forms": {
      "sg": {
        "nom": "equus",
        "gen": "equī",
        "dat": "equō",
        "acc": "equum",
        "abl": "equō"
      },
      "pl": {
        "nom": "equī",
        "gen": "equōrum",
        "dat": "equīs",
        "acc": "equōs",
        "abl": "equīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/e/eq/equus.jsonl"
  },
  "ch3-gladius": {
    "forms": {
      "sg": {
        "nom": "gladius",
        "gen": "gladiī",
        "dat": "gladiō",
        "acc": "gladium",
        "abl": "gladiō"
      },
      "pl": {
        "nom": "gladiī",
        "gen": "gladiōrum",
        "dat": "gladiīs",
        "acc": "gladiōs",
        "abl": "gladiīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/g/gl/gladius.jsonl"
  },
  "ch3-senātor": {
    "forms": {
      "sg": {
        "nom": "senātor",
        "gen": "senātōris",
        "dat": "senātōrī",
        "acc": "senātōrem",
        "abl": "senātōre"
      },
      "pl": {
        "nom": "senātōrēs",
        "gen": "senātōrum",
        "dat": "senātōribus",
        "acc": "senātōrēs",
        "abl": "senātōribus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/s/se/senator.jsonl"
  },
  "ch3-urbs": {
    "forms": {
      "sg": {
        "nom": "urbs",
        "gen": "urbis",
        "dat": "urbī",
        "acc": "urbem",
        "abl": "urbe"
      },
      "pl": {
        "nom": "urbēs",
        "gen": "urbium",
        "dat": "urbibus",
        "acc": "urbēs",
        "abl": "urbibus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/u/ur/urbs.jsonl"
  },
  "ch4-deus": {
    "forms": {
      "sg": {
        "nom": "deus",
        "gen": "deī",
        "dat": "deō",
        "acc": "deum",
        "abl": "deō"
      },
      "pl": {
        "nom": "dī",
        "gen": "deōrum",
        "dat": "dīs",
        "acc": "deōs",
        "abl": "dīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/d/de/deus.jsonl"
  },
  "ch4-dominus": {
    "forms": {
      "sg": {
        "nom": "dominus",
        "gen": "dominī",
        "dat": "dominō",
        "acc": "dominum",
        "abl": "dominō"
      },
      "pl": {
        "nom": "dominī",
        "gen": "dominōrum",
        "dat": "dominīs",
        "acc": "dominōs",
        "abl": "dominīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/d/do/dominus.jsonl"
  },
  "ch4-dōnum": {
    "forms": {
      "sg": {
        "nom": "dōnum",
        "gen": "dōnī",
        "dat": "dōnō",
        "acc": "dōnum",
        "abl": "dōnō"
      },
      "pl": {
        "nom": "dōna",
        "gen": "dōnōrum",
        "dat": "dōnīs",
        "acc": "dōna",
        "abl": "dōnīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/d/do/donum.jsonl"
  },
  "ch4-perīculum": {
    "forms": {
      "sg": {
        "nom": "perīculum",
        "gen": "perīculī",
        "dat": "perīculō",
        "acc": "perīculum",
        "abl": "perīculō"
      },
      "pl": {
        "nom": "perīcula",
        "gen": "perīculōrum",
        "dat": "perīculīs",
        "acc": "perīcula",
        "abl": "perīculīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/p/pe/periculum.jsonl"
  },
  "ch4-puella": {
    "forms": {
      "sg": {
        "nom": "puella",
        "gen": "puellae",
        "dat": "puellae",
        "acc": "puellam",
        "abl": "puellā"
      },
      "pl": {
        "nom": "puellae",
        "gen": "puellārum",
        "dat": "puellīs",
        "acc": "puellās",
        "abl": "puellīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/p/pu/puella.jsonl"
  },
  "ch4-rēx": {
    "forms": {
      "sg": {
        "nom": "rēx",
        "gen": "rēgis",
        "dat": "rēgī",
        "acc": "rēgem",
        "abl": "rēge"
      },
      "pl": {
        "nom": "rēgēs",
        "gen": "rēgum",
        "dat": "rēgibus",
        "acc": "rēgēs",
        "abl": "rēgibus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/r/re/rex.jsonl"
  },
  "ch4-templum": {
    "forms": {
      "sg": {
        "nom": "templum",
        "gen": "templī",
        "dat": "templō",
        "acc": "templum",
        "abl": "templō"
      },
      "pl": {
        "nom": "templa",
        "gen": "templōrum",
        "dat": "templīs",
        "acc": "templa",
        "abl": "templīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/t/te/templum.jsonl"
  },
  "ch5-aqua": {
    "forms": {
      "sg": {
        "nom": "aqua",
        "gen": "aquae",
        "dat": "aquae",
        "acc": "aquam",
        "abl": "aquā"
      },
      "pl": {
        "nom": "aquae",
        "gen": "aquārum",
        "dat": "aquīs",
        "acc": "aquās",
        "abl": "aquīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/a/aq/aqua.jsonl"
  },
  "ch5-custōs": {
    "forms": {
      "sg": {
        "nom": "custōs",
        "gen": "custōdis",
        "dat": "custōdī",
        "acc": "custōdem",
        "abl": "custōde"
      },
      "pl": {
        "nom": "custōdēs",
        "gen": "custōdum",
        "dat": "custōdibus",
        "acc": "custōdēs",
        "abl": "custōdibus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/c/cu/custos.jsonl"
  },
  "ch5-iuvenis": {
    "forms": {
      "sg": {
        "nom": "iuvenis",
        "gen": "iuvenis",
        "dat": "iuvenī",
        "acc": "iuvenem",
        "abl": "iuvene"
      },
      "pl": {
        "nom": "iuvenēs",
        "gen": "iuvenum",
        "dat": "iuvenibus",
        "acc": "iuvenēs",
        "abl": "iuvenibus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/i/iu/iuvenis.jsonl"
  },
  "ch5-nox": {
    "forms": {
      "sg": {
        "nom": "nox",
        "gen": "noctis",
        "dat": "noctī",
        "acc": "noctem",
        "abl": "nocte"
      },
      "pl": {
        "nom": "noctēs",
        "gen": "noctium",
        "dat": "noctibus",
        "acc": "noctēs",
        "abl": "noctibus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/n/no/nox.jsonl"
  },
  "ch6-diēs": {
    "forms": {
      "sg": {
        "nom": "diēs",
        "gen": "diēī",
        "dat": "diēī",
        "acc": "diem",
        "abl": "diē"
      },
      "pl": {
        "nom": "diēs",
        "gen": "diērum",
        "dat": "diēbus",
        "acc": "diēs",
        "abl": "diēbus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/d/di/dies.jsonl"
  },
  "ch6-marītus": {
    "forms": {
      "sg": {
        "nom": "marītus",
        "gen": "marītī",
        "dat": "marītō",
        "acc": "marītum",
        "abl": "marītō"
      },
      "pl": {
        "nom": "marītī",
        "gen": "marītōrum",
        "dat": "marītīs",
        "acc": "marītōs",
        "abl": "marītīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/m/ma/maritus.jsonl"
  },
  "ch6-māter": {
    "forms": {
      "sg": {
        "nom": "māter",
        "gen": "mātris",
        "dat": "mātrī",
        "acc": "mātrem",
        "abl": "mātre"
      },
      "pl": {
        "nom": "mātrēs",
        "gen": "mātrum",
        "dat": "mātribus",
        "acc": "mātrēs",
        "abl": "mātribus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/m/ma/mater.jsonl"
  },
  "ch6-uxor": {
    "forms": {
      "sg": {
        "nom": "uxor",
        "gen": "uxōris",
        "dat": "uxōrī",
        "acc": "uxōrem",
        "abl": "uxōre"
      },
      "pl": {
        "nom": "uxōrēs",
        "gen": "uxōrum",
        "dat": "uxōribus",
        "acc": "uxōrēs",
        "abl": "uxōribus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/u/ux/uxor.jsonl"
  },
  "ch7-epistula": {
    "forms": {
      "sg": {
        "nom": "epistula",
        "gen": "epistulae",
        "dat": "epistulae",
        "acc": "epistulam",
        "abl": "epistulā"
      },
      "pl": {
        "nom": "epistulae",
        "gen": "epistulārum",
        "dat": "epistulīs",
        "acc": "epistulās",
        "abl": "epistulīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/e/ep/epistula.jsonl"
  },
  "ch7-homō": {
    "forms": {
      "sg": {
        "nom": "homō",
        "gen": "hominis",
        "dat": "hominī",
        "acc": "hominem",
        "abl": "homine"
      },
      "pl": {
        "nom": "hominēs",
        "gen": "hominum",
        "dat": "hominibus",
        "acc": "hominēs",
        "abl": "hominibus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/h/ho/homo.jsonl"
  },
  "ch7-īnsula": {
    "forms": {
      "sg": {
        "nom": "īnsula",
        "gen": "īnsulae",
        "dat": "īnsulae",
        "acc": "īnsulam",
        "abl": "īnsulā"
      },
      "pl": {
        "nom": "īnsulae",
        "gen": "īnsulārum",
        "dat": "īnsulīs",
        "acc": "īnsulās",
        "abl": "īnsulīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/i/in/insula.jsonl"
  },
  "ch7-mīles": {
    "forms": {
      "sg": {
        "nom": "mīles",
        "gen": "mīlitis",
        "dat": "mīlitī",
        "acc": "mīlitem",
        "abl": "mīlite"
      },
      "pl": {
        "nom": "mīlitēs",
        "gen": "mīlitum",
        "dat": "mīlitibus",
        "acc": "mīlitēs",
        "abl": "mīlitibus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/m/mi/miles.jsonl"
  },
  "ch7-nauta": {
    "forms": {
      "sg": {
        "nom": "nauta",
        "gen": "nautae",
        "dat": "nautae",
        "acc": "nautam",
        "abl": "nautā"
      },
      "pl": {
        "nom": "nautae",
        "gen": "nautārum",
        "dat": "nautīs",
        "acc": "nautās",
        "abl": "nautīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/n/na/nauta.jsonl"
  },
  "ch7-pars": {
    "forms": {
      "sg": {
        "nom": "pars",
        "gen": "partis",
        "dat": "partī",
        "acc": "partem",
        "abl": "parte"
      },
      "pl": {
        "nom": "partēs",
        "gen": "partium",
        "dat": "partibus",
        "acc": "partēs",
        "abl": "partibus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/p/pa/pars.jsonl"
  },
  "ch7-puer": {
    "forms": {
      "sg": {
        "nom": "puer",
        "gen": "puerī",
        "dat": "puerō",
        "acc": "puerum",
        "abl": "puerō"
      },
      "pl": {
        "nom": "puerī",
        "gen": "puerōrum",
        "dat": "puerīs",
        "acc": "puerōs",
        "abl": "puerīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/p/pu/puer.jsonl"
  },
  "ch7-rēs": {
    "forms": {
      "sg": {
        "nom": "rēs",
        "gen": "reī",
        "dat": "reī",
        "acc": "rem",
        "abl": "rē"
      },
      "pl": {
        "nom": "rēs",
        "gen": "rērum",
        "dat": "rēbus",
        "acc": "rēs",
        "abl": "rēbus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/r/re/res.jsonl"
  },
  "ch7-silva": {
    "forms": {
      "sg": {
        "nom": "silva",
        "gen": "silvae",
        "dat": "silvae",
        "acc": "silvam",
        "abl": "silvā"
      },
      "pl": {
        "nom": "silvae",
        "gen": "silvārum",
        "dat": "silvīs",
        "acc": "silvās",
        "abl": "silvīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/s/si/silva.jsonl"
  },
  "ch8-domus": {
    "forms": {
      "sg": {
        "nom": "domus",
        "gen": "domūs",
        "dat": "domuī",
        "acc": "domum",
        "abl": "domū"
      },
      "pl": {
        "nom": "domūs",
        "gen": "domuum",
        "dat": "domibus",
        "acc": "domūs",
        "abl": "domibus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/d/do/domus.jsonl",
    "review": "marked irregular in the vocab data; Wiktionary marks it irregular (\"domus f (genitive domūs or domī); irregular, variously declined, fourth declension, second declension\")"
  },
  "ch8-porta": {
    "forms": {
      "sg": {
        "nom": "porta",
        "gen": "portae",
        "dat": "portae",
        "acc": "portam",
        "abl": "portā"
      },
      "pl": {
        "nom": "portae",
        "gen": "portārum",
        "dat": "portīs",
        "acc": "portās",
        "abl": "portīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/p/po/porta.jsonl"
  },
  "ch8-senex": {
    "forms": {
      "sg": {
        "nom": "senex",
        "gen": "senis",
        "dat": "senī",
        "acc": "senem",
        "abl": "sene"
      },
      "pl": {
        "nom": "senēs",
        "gen": "senum",
        "dat": "senibus",
        "acc": "senēs",
        "abl": "senibus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/s/se/senex.jsonl"
  },
  "ch9-cīvis": {
    "forms": {
      "sg": {
        "nom": "cīvis",
        "gen": "cīvis",
        "dat": "cīvī",
        "acc": "cīvem",
        "abl": "cīve"
      },
      "pl": {
        "nom": "cīvēs",
        "gen": "cīvium",
        "dat": "cīvibus",
        "acc": "cīvēs",
        "abl": "cīvibus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/c/ci/civis.jsonl"
  },
  "ch9-domina": {
    "forms": {
      "sg": {
        "nom": "domina",
        "gen": "dominae",
        "dat": "dominae",
        "acc": "dominam",
        "abl": "dominā"
      },
      "pl": {
        "nom": "dominae",
        "gen": "dominārum",
        "dat": "dominīs",
        "acc": "dominās",
        "abl": "dominīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/d/do/domina.jsonl"
  },
  "ch9-hostis": {
    "forms": {
      "sg": {
        "nom": "hostis",
        "gen": "hostis",
        "dat": "hostī",
        "acc": "hostem",
        "abl": "hoste"
      },
      "pl": {
        "nom": "hostēs",
        "gen": "hostium",
        "dat": "hostibus",
        "acc": "hostēs",
        "abl": "hostibus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/h/ho/hostis.jsonl"
  },
  "ch9-imperātor": {
    "forms": {
      "sg": {
        "nom": "imperātor",
        "gen": "imperātōris",
        "dat": "imperātōrī",
        "acc": "imperātōrem",
        "abl": "imperātōre"
      },
      "pl": {
        "nom": "imperātōrēs",
        "gen": "imperātōrum",
        "dat": "imperātōribus",
        "acc": "imperātōrēs",
        "abl": "imperātōribus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/i/im/imperator.jsonl"
  },
  "ch9-iter": {
    "forms": {
      "sg": {
        "nom": "iter",
        "gen": "itineris",
        "dat": "itinerī",
        "acc": "iter",
        "abl": "itinere"
      },
      "pl": {
        "nom": "itinera",
        "gen": "itinerum",
        "dat": "itineribus",
        "acc": "itinera",
        "abl": "itineribus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/i/it/iter.jsonl"
  },
  "ch9-sanguis": {
    "forms": {
      "sg": {
        "nom": "sanguis",
        "gen": "sanguinis",
        "dat": "sanguinī",
        "acc": "sanguinem",
        "abl": "sanguine"
      },
      "pl": {
        "nom": "sanguinēs",
        "gen": "sanguinum",
        "dat": "sanguinibus",
        "acc": "sanguinēs",
        "abl": "sanguinibus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/s/sa/sanguis.jsonl"
  },
  "ch9-vir": {
    "forms": {
      "sg": {
        "nom": "vir",
        "gen": "virī",
        "dat": "virō",
        "acc": "virum",
        "abl": "virō"
      },
      "pl": {
        "nom": "virī",
        "gen": "virōrum",
        "dat": "virīs",
        "acc": "virōs",
        "abl": "virīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/v/vi/vir.jsonl"
  },
  "ch9-vīta": {
    "forms": {
      "sg": {
        "nom": "vīta",
        "gen": "vītae",
        "dat": "vītae",
        "acc": "vītam",
        "abl": "vītā"
      },
      "pl": {
        "nom": "vītae",
        "gen": "vītārum",
        "dat": "vītīs",
        "acc": "vītās",
        "abl": "vītīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/v/vi/vita.jsonl"
  },
  "ch10-annus": {
    "forms": {
      "sg": {
        "nom": "annus",
        "gen": "annī",
        "dat": "annō",
        "acc": "annum",
        "abl": "annō"
      },
      "pl": {
        "nom": "annī",
        "gen": "annōrum",
        "dat": "annīs",
        "acc": "annōs",
        "abl": "annīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/a/an/annus.jsonl"
  },
  "ch10-dea": {
    "forms": {
      "sg": {
        "nom": "dea",
        "gen": "deae",
        "dat": "deae",
        "acc": "deam",
        "abl": "deā"
      },
      "pl": {
        "nom": "deae",
        "gen": "deārum",
        "dat": "deābus",
        "acc": "deās",
        "abl": "deābus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/d/de/dea.jsonl"
  },
  "ch10-locus": {
    "forms": {
      "sg": {
        "nom": "locus",
        "gen": "locī",
        "dat": "locō",
        "acc": "locum",
        "abl": "locō"
      },
      "pl": {
        "nom": "locī",
        "gen": "locōrum",
        "dat": "locīs",
        "acc": "locōs",
        "abl": "locīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/l/lo/locus.jsonl"
  },
  "ch10-pāx": {
    "forms": {
      "sg": {
        "nom": "pāx",
        "gen": "pācis",
        "dat": "pācī",
        "acc": "pācem",
        "abl": "pāce"
      },
      "pl": {
        "nom": "pācēs",
        "gen": "pācum",
        "dat": "pācibus",
        "acc": "pācēs",
        "abl": "pācibus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/p/pa/pax.jsonl"
  },
  "ch11-dux": {
    "forms": {
      "sg": {
        "nom": "dux",
        "gen": "ducis",
        "dat": "ducī",
        "acc": "ducem",
        "abl": "duce"
      },
      "pl": {
        "nom": "ducēs",
        "gen": "ducum",
        "dat": "ducibus",
        "acc": "ducēs",
        "abl": "ducibus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/d/du/dux.jsonl"
  },
  "ch11-flūmen": {
    "forms": {
      "sg": {
        "nom": "flūmen",
        "gen": "flūminis",
        "dat": "flūminī",
        "acc": "flūmen",
        "abl": "flūmine"
      },
      "pl": {
        "nom": "flūmina",
        "gen": "flūminum",
        "dat": "flūminibus",
        "acc": "flūmina",
        "abl": "flūminibus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/f/fl/flumen.jsonl"
  },
  "ch11-mare": {
    "forms": {
      "sg": {
        "nom": "mare",
        "gen": "maris",
        "dat": "marī",
        "acc": "mare",
        "abl": "marī"
      },
      "pl": {
        "nom": "maria",
        "gen": "marium",
        "dat": "maribus",
        "acc": "maria",
        "abl": "maribus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/m/ma/mare.jsonl"
  },
  "ch11-nāvis": {
    "forms": {
      "sg": {
        "nom": "nāvis",
        "gen": "nāvis",
        "dat": "nāvī",
        "acc": "nāvem",
        "abl": "nāve"
      },
      "pl": {
        "nom": "nāvēs",
        "gen": "nāvium",
        "dat": "nāvibus",
        "acc": "nāvēs",
        "abl": "nāvibus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/n/na/navis.jsonl"
  },
  "ch12-caelum": {
    "forms": {
      "sg": {
        "nom": "caelum",
        "gen": "caelī",
        "dat": "caelō",
        "acc": "caelum",
        "abl": "caelō"
      },
      "pl": {
        "nom": "caela",
        "gen": "caelōrum",
        "dat": "caelīs",
        "acc": "caela",
        "abl": "caelīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/c/ca/caelum.jsonl"
  },
  "ch12-caput": {
    "forms": {
      "sg": {
        "nom": "caput",
        "gen": "capitis",
        "dat": "capitī",
        "acc": "caput",
        "abl": "capite"
      },
      "pl": {
        "nom": "capita",
        "gen": "capitum",
        "dat": "capitibus",
        "acc": "capita",
        "abl": "capitibus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/c/ca/caput.jsonl"
  },
  "ch12-corpus": {
    "forms": {
      "sg": {
        "nom": "corpus",
        "gen": "corporis",
        "dat": "corporī",
        "acc": "corpus",
        "abl": "corpore"
      },
      "pl": {
        "nom": "corpora",
        "gen": "corporum",
        "dat": "corporibus",
        "acc": "corpora",
        "abl": "corporibus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/c/co/corpus.jsonl"
  },
  "ch12-iānua": {
    "forms": {
      "sg": {
        "nom": "iānua",
        "gen": "iānuae",
        "dat": "iānuae",
        "acc": "iānuam",
        "abl": "iānuā"
      },
      "pl": {
        "nom": "iānuae",
        "gen": "iānuārum",
        "dat": "iānuīs",
        "acc": "iānuās",
        "abl": "iānuīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/i/ia/ianua.jsonl"
  },
  "ch12-taberna": {
    "forms": {
      "sg": {
        "nom": "taberna",
        "gen": "tabernae",
        "dat": "tabernae",
        "acc": "tabernam",
        "abl": "tabernā"
      },
      "pl": {
        "nom": "tabernae",
        "gen": "tabernārum",
        "dat": "tabernīs",
        "acc": "tabernās",
        "abl": "tabernīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/t/ta/taberna.jsonl"
  },
  "ch12-terra": {
    "forms": {
      "sg": {
        "nom": "terra",
        "gen": "terrae",
        "dat": "terrae",
        "acc": "terram",
        "abl": "terrā"
      },
      "pl": {
        "nom": "terrae",
        "gen": "terrārum",
        "dat": "terrīs",
        "acc": "terrās",
        "abl": "terrīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/t/te/terra.jsonl"
  },
  "ch12-vōx": {
    "forms": {
      "sg": {
        "nom": "vōx",
        "gen": "vōcis",
        "dat": "vōcī",
        "acc": "vōcem",
        "abl": "vōce"
      },
      "pl": {
        "nom": "vōcēs",
        "gen": "vōcum",
        "dat": "vōcibus",
        "acc": "vōcēs",
        "abl": "vōcibus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/v/vo/vox.jsonl"
  },
  "ch13-labor": {
    "forms": {
      "sg": {
        "nom": "labor",
        "gen": "labōris",
        "dat": "labōrī",
        "acc": "labōrem",
        "abl": "labōre"
      },
      "pl": {
        "nom": "labōrēs",
        "gen": "labōrum",
        "dat": "labōribus",
        "acc": "labōrēs",
        "abl": "labōribus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/l/la/labor.jsonl"
  },
  "ch13-mūrus": {
    "forms": {
      "sg": {
        "nom": "mūrus",
        "gen": "mūrī",
        "dat": "mūrō",
        "acc": "mūrum",
        "abl": "mūrō"
      },
      "pl": {
        "nom": "mūrī",
        "gen": "mūrōrum",
        "dat": "mūrīs",
        "acc": "mūrōs",
        "abl": "mūrīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/m/mu/murus.jsonl"
  },
  "ch13-nōmen": {
    "forms": {
      "sg": {
        "nom": "nōmen",
        "gen": "nōminis",
        "dat": "nōminī",
        "acc": "nōmen",
        "abl": "nōmine"
      },
      "pl": {
        "nom": "nōmina",
        "gen": "nōminum",
        "dat": "nōminibus",
        "acc": "nōmina",
        "abl": "nōminibus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/n/no/nomen.jsonl"
  },
  "ch13-praemium": {
    "forms": {
      "sg": {
        "nom": "praemium",
        "gen": "praemiī",
        "dat": "praemiō",
        "acc": "praemium",
        "abl": "praemiō"
      },
      "pl": {
        "nom": "praemia",
        "gen": "praemiōrum",
        "dat": "praemiīs",
        "acc": "praemia",
        "abl": "praemiīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/p/pr/praemium.jsonl"
  },
  "ch14-amor": {
    "forms": {
      "sg": {
        "nom": "amor",
        "gen": "amōris",
        "dat": "amōrī",
        "acc": "amōrem",
        "abl": "amōre"
      },
      "pl": {
        "nom": "amōrēs",
        "gen": "amōrum",
        "dat": "amōribus",
        "acc": "amōrēs",
        "abl": "amōribus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/a/am/amor.jsonl"
  },
  "ch14-cōnsilium": {
    "forms": {
      "sg": {
        "nom": "cōnsilium",
        "gen": "cōnsiliī",
        "dat": "cōnsiliō",
        "acc": "cōnsilium",
        "abl": "cōnsiliō"
      },
      "pl": {
        "nom": "cōnsilia",
        "gen": "cōnsiliōrum",
        "dat": "cōnsiliīs",
        "acc": "cōnsilia",
        "abl": "cōnsiliīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/c/co/consilium.jsonl"
  },
  "ch14-fēmina": {
    "forms": {
      "sg": {
        "nom": "fēmina",
        "gen": "fēminae",
        "dat": "fēminae",
        "acc": "fēminam",
        "abl": "fēminā"
      },
      "pl": {
        "nom": "fēminae",
        "gen": "fēminārum",
        "dat": "fēminīs",
        "acc": "fēminās",
        "abl": "fēminīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/f/fe/femina.jsonl"
  },
  "ch14-mōns": {
    "forms": {
      "sg": {
        "nom": "mōns",
        "gen": "montis",
        "dat": "montī",
        "acc": "montem",
        "abl": "monte"
      },
      "pl": {
        "nom": "montēs",
        "gen": "montium",
        "dat": "montibus",
        "acc": "montēs",
        "abl": "montibus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/m/mo/mons.jsonl"
  },
  "ch14-mors": {
    "forms": {
      "sg": {
        "nom": "mors",
        "gen": "mortis",
        "dat": "mortī",
        "acc": "mortem",
        "abl": "morte"
      },
      "pl": {
        "nom": "mortēs",
        "gen": "mortium",
        "dat": "mortibus",
        "acc": "mortēs",
        "abl": "mortibus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/m/mo/mors.jsonl"
  },
  "ch14-tempus": {
    "forms": {
      "sg": {
        "nom": "tempus",
        "gen": "temporis",
        "dat": "temporī",
        "acc": "tempus",
        "abl": "tempore"
      },
      "pl": {
        "nom": "tempora",
        "gen": "temporum",
        "dat": "temporibus",
        "acc": "tempora",
        "abl": "temporibus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/t/te/tempus.jsonl"
  },
  "ch14-verbum": {
    "forms": {
      "sg": {
        "nom": "verbum",
        "gen": "verbī",
        "dat": "verbō",
        "acc": "verbum",
        "abl": "verbō"
      },
      "pl": {
        "nom": "verba",
        "gen": "verbōrum",
        "dat": "verbīs",
        "acc": "verba",
        "abl": "verbīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/v/ve/verbum.jsonl"
  },
  "ch15-bellum": {
    "forms": {
      "sg": {
        "nom": "bellum",
        "gen": "bellī",
        "dat": "bellō",
        "acc": "bellum",
        "abl": "bellō"
      },
      "pl": {
        "nom": "bella",
        "gen": "bellōrum",
        "dat": "bellīs",
        "acc": "bella",
        "abl": "bellīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/b/be/bellum.jsonl"
  },
  "ch15-cēna": {
    "forms": {
      "sg": {
        "nom": "cēna",
        "gen": "cēnae",
        "dat": "cēnae",
        "acc": "cēnam",
        "abl": "cēnā"
      },
      "pl": {
        "nom": "cēnae",
        "gen": "cēnārum",
        "dat": "cēnīs",
        "acc": "cēnās",
        "abl": "cēnīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/c/ce/cena.jsonl"
  },
  "ch15-comes": {
    "forms": {
      "sg": {
        "nom": "comes",
        "gen": "comitis",
        "dat": "comitī",
        "acc": "comitem",
        "abl": "comite"
      },
      "pl": {
        "nom": "comitēs",
        "gen": "comitum",
        "dat": "comitibus",
        "acc": "comitēs",
        "abl": "comitibus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/c/co/comes.jsonl"
  },
  "ch15-hortus": {
    "forms": {
      "sg": {
        "nom": "hortus",
        "gen": "hortī",
        "dat": "hortō",
        "acc": "hortum",
        "abl": "hortō"
      },
      "pl": {
        "nom": "hortī",
        "gen": "hortōrum",
        "dat": "hortīs",
        "acc": "hortōs",
        "abl": "hortīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/h/ho/hortus.jsonl"
  },
  "ch15-lībertus": {
    "forms": {
      "sg": {
        "nom": "lībertus",
        "gen": "lībertī",
        "dat": "lībertō",
        "acc": "lībertum",
        "abl": "lībertō"
      },
      "pl": {
        "nom": "lībertī",
        "gen": "lībertōrum",
        "dat": "lībertīs",
        "acc": "lībertōs",
        "abl": "lībertīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/l/li/libertus.jsonl"
  },
  "ch15-vīlla": {
    "forms": {
      "sg": {
        "nom": "vīlla",
        "gen": "vīllae",
        "dat": "vīllae",
        "acc": "vīllam",
        "abl": "vīllā"
      },
      "pl": {
        "nom": "vīllae",
        "gen": "vīllārum",
        "dat": "vīllīs",
        "acc": "vīllās",
        "abl": "vīllīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/v/vi/villa.jsonl"
  },
  "ch16-imperium": {
    "forms": {
      "sg": {
        "nom": "imperium",
        "gen": "imperiī",
        "dat": "imperiō",
        "acc": "imperium",
        "abl": "imperiō"
      },
      "pl": {
        "nom": "imperia",
        "gen": "imperiōrum",
        "dat": "imperiīs",
        "acc": "imperia",
        "abl": "imperiīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/i/im/imperium.jsonl"
  },
  "ch16-lūx": {
    "forms": {
      "sg": {
        "nom": "lūx",
        "gen": "lūcis",
        "dat": "lūcī",
        "acc": "lūcem",
        "abl": "lūce"
      },
      "pl": {
        "nom": "lūcēs",
        "gen": "lūcum",
        "dat": "lūcibus",
        "acc": "lūcēs",
        "abl": "lūcibus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/l/lu/lux.jsonl"
  },
  "ch16-prīnceps": {
    "forms": {
      "sg": {
        "nom": "prīnceps",
        "gen": "prīncipis",
        "dat": "prīncipī",
        "acc": "prīncipem",
        "abl": "prīncipe"
      },
      "pl": {
        "nom": "prīncipēs",
        "gen": "prīncipum",
        "dat": "prīncipibus",
        "acc": "prīncipēs",
        "abl": "prīncipibus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/p/pr/princeps.jsonl"
  },
  "ch16-rēgīna": {
    "forms": {
      "sg": {
        "nom": "rēgīna",
        "gen": "rēgīnae",
        "dat": "rēgīnae",
        "acc": "rēgīnam",
        "abl": "rēgīnā"
      },
      "pl": {
        "nom": "rēgīnae",
        "gen": "rēgīnārum",
        "dat": "rēgīnīs",
        "acc": "rēgīnās",
        "abl": "rēgīnīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/r/re/regina.jsonl"
  },
  "ch17-sōl": {
    "forms": {
      "sg": {
        "nom": "sōl",
        "gen": "sōlis",
        "dat": "sōlī",
        "acc": "sōlem",
        "abl": "sōle"
      },
      "pl": {
        "nom": "sōlēs",
        "gen": "sōlum",
        "dat": "sōlibus",
        "acc": "sōlēs",
        "abl": "sōlibus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/s/so/sol.jsonl"
  },
  "ch17-unda": {
    "forms": {
      "sg": {
        "nom": "unda",
        "gen": "undae",
        "dat": "undae",
        "acc": "undam",
        "abl": "undā"
      },
      "pl": {
        "nom": "undae",
        "gen": "undārum",
        "dat": "undīs",
        "acc": "undās",
        "abl": "undīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/u/un/unda.jsonl"
  },
  "ch18-animus": {
    "forms": {
      "sg": {
        "nom": "animus",
        "gen": "animī",
        "dat": "animō",
        "acc": "animum",
        "abl": "animō"
      },
      "pl": {
        "nom": "animī",
        "gen": "animōrum",
        "dat": "animīs",
        "acc": "animōs",
        "abl": "animīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/a/an/animus.jsonl"
  },
  "ch18-eques": {
    "forms": {
      "sg": {
        "nom": "eques",
        "gen": "equitis",
        "dat": "equitī",
        "acc": "equitem",
        "abl": "equite"
      },
      "pl": {
        "nom": "equitēs",
        "gen": "equitum",
        "dat": "equitibus",
        "acc": "equitēs",
        "abl": "equitibus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/e/eq/eques.jsonl"
  },
  "ch18-legiō": {
    "forms": {
      "sg": {
        "nom": "legiō",
        "gen": "legiōnis",
        "dat": "legiōnī",
        "acc": "legiōnem",
        "abl": "legiōne"
      },
      "pl": {
        "nom": "legiōnēs",
        "gen": "legiōnum",
        "dat": "legiōnibus",
        "acc": "legiōnēs",
        "abl": "legiōnibus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/l/le/legio.jsonl"
  },
  "ch18-umbra": {
    "forms": {
      "sg": {
        "nom": "umbra",
        "gen": "umbrae",
        "dat": "umbrae",
        "acc": "umbram",
        "abl": "umbrā"
      },
      "pl": {
        "nom": "umbrae",
        "gen": "umbrārum",
        "dat": "umbrīs",
        "acc": "umbrās",
        "abl": "umbrīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/u/um/umbra.jsonl"
  },
  "ch19-lacrima": {
    "forms": {
      "sg": {
        "nom": "lacrima",
        "gen": "lacrimae",
        "dat": "lacrimae",
        "acc": "lacrimam",
        "abl": "lacrimā"
      },
      "pl": {
        "nom": "lacrimae",
        "gen": "lacrimārum",
        "dat": "lacrimīs",
        "acc": "lacrimās",
        "abl": "lacrimīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/l/la/lacrima.jsonl"
  },
  "ch19-oculus": {
    "forms": {
      "sg": {
        "nom": "oculus",
        "gen": "oculī",
        "dat": "oculō",
        "acc": "oculum",
        "abl": "oculō"
      },
      "pl": {
        "nom": "oculī",
        "gen": "oculōrum",
        "dat": "oculīs",
        "acc": "oculōs",
        "abl": "oculīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/o/oc/oculus.jsonl"
  },
  "ch19-vestīmentum": {
    "forms": {
      "sg": {
        "nom": "vestīmentum",
        "gen": "vestīmentī",
        "dat": "vestīmentō",
        "acc": "vestīmentum",
        "abl": "vestīmentō"
      },
      "pl": {
        "nom": "vestīmenta",
        "gen": "vestīmentōrum",
        "dat": "vestīmentīs",
        "acc": "vestīmenta",
        "abl": "vestīmentīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/v/ve/vestimentum.jsonl"
  },
  "ch19-vōtum": {
    "forms": {
      "sg": {
        "nom": "vōtum",
        "gen": "vōtī",
        "dat": "vōtō",
        "acc": "vōtum",
        "abl": "vōtō"
      },
      "pl": {
        "nom": "vōta",
        "gen": "vōtōrum",
        "dat": "vōtīs",
        "acc": "vōta",
        "abl": "vōtīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/v/vo/votum.jsonl"
  },
  "ch19-vulnus": {
    "forms": {
      "sg": {
        "nom": "vulnus",
        "gen": "vulneris",
        "dat": "vulnerī",
        "acc": "vulnus",
        "abl": "vulnere"
      },
      "pl": {
        "nom": "vulnera",
        "gen": "vulnerum",
        "dat": "vulneribus",
        "acc": "vulnera",
        "abl": "vulneribus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/v/vu/vulnus.jsonl"
  },
  "ch20-fuga": {
    "forms": {
      "sg": {
        "nom": "fuga",
        "gen": "fugae",
        "dat": "fugae",
        "acc": "fugam",
        "abl": "fugā"
      },
      "pl": {
        "nom": "fugae",
        "gen": "fugārum",
        "dat": "fugīs",
        "acc": "fugās",
        "abl": "fugīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/f/fu/fuga.jsonl"
  },
  "ch20-lībertās": {
    "forms": {
      "sg": {
        "nom": "lībertās",
        "gen": "lībertātis",
        "dat": "lībertātī",
        "acc": "lībertātem",
        "abl": "lībertāte"
      },
      "pl": {
        "nom": "lībertātēs",
        "gen": "lībertātum",
        "dat": "lībertātibus",
        "acc": "lībertātēs",
        "abl": "lībertātibus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/l/li/libertas.jsonl"
  },
  "ch20-tēlum": {
    "forms": {
      "sg": {
        "nom": "tēlum",
        "gen": "tēlī",
        "dat": "tēlō",
        "acc": "tēlum",
        "abl": "tēlō"
      },
      "pl": {
        "nom": "tēla",
        "gen": "tēlōrum",
        "dat": "tēlīs",
        "acc": "tēla",
        "abl": "tēlīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/t/te/telum.jsonl"
  },
  "ch21-auris": {
    "forms": {
      "sg": {
        "nom": "auris",
        "gen": "auris",
        "dat": "aurī",
        "acc": "aurem",
        "abl": "aure"
      },
      "pl": {
        "nom": "aurēs",
        "gen": "aurium",
        "dat": "auribus",
        "acc": "aurēs",
        "abl": "auribus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/a/au/auris.jsonl"
  },
  "ch21-gaudium": {
    "forms": {
      "sg": {
        "nom": "gaudium",
        "gen": "gaudiī",
        "dat": "gaudiō",
        "acc": "gaudium",
        "abl": "gaudiō"
      },
      "pl": {
        "nom": "gaudia",
        "gen": "gaudiōrum",
        "dat": "gaudiīs",
        "acc": "gaudia",
        "abl": "gaudiīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/g/ga/gaudium.jsonl"
  },
  "ch21-ignis": {
    "forms": {
      "sg": {
        "nom": "ignis",
        "gen": "ignis",
        "dat": "ignī",
        "acc": "ignem",
        "abl": "ignī"
      },
      "pl": {
        "nom": "ignēs",
        "gen": "ignium",
        "dat": "ignibus",
        "acc": "ignēs",
        "abl": "ignibus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/i/ig/ignis.jsonl"
  },
  "ch21-pēs": {
    "forms": {
      "sg": {
        "nom": "pēs",
        "gen": "pedis",
        "dat": "pedī",
        "acc": "pedem",
        "abl": "pede"
      },
      "pl": {
        "nom": "pedēs",
        "gen": "pedum",
        "dat": "pedibus",
        "acc": "pedēs",
        "abl": "pedibus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/p/pe/pes.jsonl"
  },
  "ch21-poena": {
    "forms": {
      "sg": {
        "nom": "poena",
        "gen": "poenae",
        "dat": "poenae",
        "acc": "poenam",
        "abl": "poenā"
      },
      "pl": {
        "nom": "poenae",
        "gen": "poenārum",
        "dat": "poenīs",
        "acc": "poenās",
        "abl": "poenīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/p/po/poena.jsonl"
  },
  "ch21-tēctum": {
    "forms": {
      "sg": {
        "nom": "tēctum",
        "gen": "tēctī",
        "dat": "tēctō",
        "acc": "tēctum",
        "abl": "tēctō"
      },
      "pl": {
        "nom": "tēcta",
        "gen": "tēctōrum",
        "dat": "tēctīs",
        "acc": "tēcta",
        "abl": "tēctīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/t/te/tectum.jsonl"
  },
  "ch21-ventus": {
    "forms": {
      "sg": {
        "nom": "ventus",
        "gen": "ventī",
        "dat": "ventō",
        "acc": "ventum",
        "abl": "ventō"
      },
      "pl": {
        "nom": "ventī",
        "gen": "ventōrum",
        "dat": "ventīs",
        "acc": "ventōs",
        "abl": "ventīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/v/ve/ventus.jsonl"
  },
  "ch22-canis": {
    "forms": {
      "sg": {
        "nom": "canis",
        "gen": "canis",
        "dat": "canī",
        "acc": "canem",
        "abl": "cane"
      },
      "pl": {
        "nom": "canēs",
        "gen": "canum",
        "dat": "canibus",
        "acc": "canēs",
        "abl": "canibus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/c/ca/canis.jsonl"
  },
  "ch22-cūra": {
    "forms": {
      "sg": {
        "nom": "cūra",
        "gen": "cūrae",
        "dat": "cūrae",
        "acc": "cūram",
        "abl": "cūrā"
      },
      "pl": {
        "nom": "cūrae",
        "gen": "cūrārum",
        "dat": "cūrīs",
        "acc": "cūrās",
        "abl": "cūrīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/c/cu/cura.jsonl"
  },
  "ch23-parēns": {
    "forms": {
      "sg": {
        "nom": "parēns",
        "gen": "parentis",
        "dat": "parentī",
        "acc": "parentem",
        "abl": "parente"
      },
      "pl": {
        "nom": "parentēs",
        "gen": "parentum",
        "dat": "parentibus",
        "acc": "parentēs",
        "abl": "parentibus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/p/pa/parens.jsonl"
  },
  "ch23-signum": {
    "forms": {
      "sg": {
        "nom": "signum",
        "gen": "signī",
        "dat": "signō",
        "acc": "signum",
        "abl": "signō"
      },
      "pl": {
        "nom": "signa",
        "gen": "signōrum",
        "dat": "signīs",
        "acc": "signa",
        "abl": "signīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/s/si/signum.jsonl"
  },
  "ch23-soror": {
    "forms": {
      "sg": {
        "nom": "soror",
        "gen": "sorōris",
        "dat": "sorōrī",
        "acc": "sorōrem",
        "abl": "sorōre"
      },
      "pl": {
        "nom": "sorōrēs",
        "gen": "sorōrum",
        "dat": "sorōribus",
        "acc": "sorōrēs",
        "abl": "sorōribus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/s/so/soror.jsonl"
  },
  "ch24-exercitus": {
    "forms": {
      "sg": {
        "nom": "exercitus",
        "gen": "exercitūs",
        "dat": "exercituī",
        "acc": "exercitum",
        "abl": "exercitū"
      },
      "pl": {
        "nom": "exercitūs",
        "gen": "exercituum",
        "dat": "exercitibus",
        "acc": "exercitūs",
        "abl": "exercitibus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/e/ex/exercitus.jsonl"
  },
  "ch24-manus": {
    "forms": {
      "sg": {
        "nom": "manus",
        "gen": "manūs",
        "dat": "manuī",
        "acc": "manum",
        "abl": "manū"
      },
      "pl": {
        "nom": "manūs",
        "gen": "manuum",
        "dat": "manibus",
        "acc": "manūs",
        "abl": "manibus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/m/ma/manus.jsonl"
  },
  "ch24-opus": {
    "forms": {
      "sg": {
        "nom": "opus",
        "gen": "operis",
        "dat": "operī",
        "acc": "opus",
        "abl": "opere"
      },
      "pl": {
        "nom": "opera",
        "gen": "operum",
        "dat": "operibus",
        "acc": "opera",
        "abl": "operibus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/o/op/opus.jsonl"
  },
  "ch24-saxum": {
    "forms": {
      "sg": {
        "nom": "saxum",
        "gen": "saxī",
        "dat": "saxō",
        "acc": "saxum",
        "abl": "saxō"
      },
      "pl": {
        "nom": "saxa",
        "gen": "saxōrum",
        "dat": "saxīs",
        "acc": "saxa",
        "abl": "saxīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/s/sa/saxum.jsonl"
  },
  "ch24-vultus": {
    "forms": {
      "sg": {
        "nom": "vultus",
        "gen": "vultūs",
        "dat": "vultuī",
        "acc": "vultum",
        "abl": "vultū"
      },
      "pl": {
        "nom": "vultūs",
        "gen": "vultuum",
        "dat": "vultibus",
        "acc": "vultūs",
        "abl": "vultibus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/v/vu/vultus.jsonl"
  },
  "ch25-faciēs": {
    "forms": {
      "sg": {
        "nom": "faciēs",
        "gen": "faciēī",
        "dat": "faciēī",
        "acc": "faciem",
        "abl": "faciē"
      },
      "pl": {
        "nom": "faciēs",
        "gen": "faciērum",
        "dat": "faciēbus",
        "acc": "faciēs",
        "abl": "faciēbus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/f/fa/facies.jsonl"
  },
  "ch25-imperium": {
    "forms": {
      "sg": {
        "nom": "imperium",
        "gen": "imperiī",
        "dat": "imperiō",
        "acc": "imperium",
        "abl": "imperiō"
      },
      "pl": {
        "nom": "imperia",
        "gen": "imperiōrum",
        "dat": "imperiīs",
        "acc": "imperia",
        "abl": "imperiīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/i/im/imperium.jsonl"
  },
  "ch25-lēgātus": {
    "forms": {
      "sg": {
        "nom": "lēgātus",
        "gen": "lēgātī",
        "dat": "lēgātō",
        "acc": "lēgātum",
        "abl": "lēgātō"
      },
      "pl": {
        "nom": "lēgātī",
        "gen": "lēgātōrum",
        "dat": "lēgātīs",
        "acc": "lēgātōs",
        "abl": "lēgātīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/l/le/legatus.jsonl"
  },
  "ch25-rēs": {
    "forms": {
      "sg": {
        "nom": "rēs",
        "gen": "reī",
        "dat": "reī",
        "acc": "rem",
        "abl": "rē"
      },
      "pl": {
        "nom": "rēs",
        "gen": "rērum",
        "dat": "rēbus",
        "acc": "rēs",
        "abl": "rēbus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/r/re/res.jsonl"
  },
  "ch25-spēs": {
    "forms": {
      "sg": {
        "nom": "spēs",
        "gen": "spēī",
        "dat": "spēī",
        "acc": "spem",
        "abl": "spē"
      },
      "pl": {
        "nom": "spēs",
        "gen": "spērum",
        "dat": "spēbus",
        "acc": "spēs",
        "abl": "spēbus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/s/sp/spes.jsonl"
  },
  "ch25-victōria": {
    "forms": {
      "sg": {
        "nom": "victōria",
        "gen": "victōriae",
        "dat": "victōriae",
        "acc": "victōriam",
        "abl": "victōriā"
      },
      "pl": {
        "nom": "victōriae",
        "gen": "victōriārum",
        "dat": "victōriīs",
        "acc": "victōriās",
        "abl": "victōriīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/v/vi/victoria.jsonl"
  },
  "ch26-carmen": {
    "forms": {
      "sg": {
        "nom": "carmen",
        "gen": "carminis",
        "dat": "carminī",
        "acc": "carmen",
        "abl": "carmine"
      },
      "pl": {
        "nom": "carmina",
        "gen": "carminum",
        "dat": "carminibus",
        "acc": "carmina",
        "abl": "carminibus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/c/ca/carmen.jsonl"
  },
  "ch26-fātum": {
    "forms": {
      "sg": {
        "nom": "fātum",
        "gen": "fātī",
        "dat": "fātō",
        "acc": "fātum",
        "abl": "fātō"
      },
      "pl": {
        "nom": "fāta",
        "gen": "fātōrum",
        "dat": "fātīs",
        "acc": "fāta",
        "abl": "fātīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/f/fa/fatum.jsonl"
  },
  "ch26-īra": {
    "forms": {
      "sg": {
        "nom": "īra",
        "gen": "īrae",
        "dat": "īrae",
        "acc": "īram",
        "abl": "īrā"
      },
      "pl": {
        "nom": "īrae",
        "gen": "īrārum",
        "dat": "īrīs",
        "acc": "īrās",
        "abl": "īrīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/i/ir/ira.jsonl"
  },
  "ch26-modus": {
    "forms": {
      "sg": {
        "nom": "modus",
        "gen": "modī",
        "dat": "modō",
        "acc": "modum",
        "abl": "modō"
      },
      "pl": {
        "nom": "modī",
        "gen": "modōrum",
        "dat": "modīs",
        "acc": "modōs",
        "abl": "modīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/m/mo/modus.jsonl"
  },
  "ch27-arbor": {
    "forms": {
      "sg": {
        "nom": "arbor",
        "gen": "arboris",
        "dat": "arborī",
        "acc": "arborem",
        "abl": "arbore"
      },
      "pl": {
        "nom": "arborēs",
        "gen": "arborum",
        "dat": "arboribus",
        "acc": "arborēs",
        "abl": "arboribus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/a/ar/arbor.jsonl"
  },
  "ch27-ars": {
    "forms": {
      "sg": {
        "nom": "ars",
        "gen": "artis",
        "dat": "artī",
        "acc": "artem",
        "abl": "arte"
      },
      "pl": {
        "nom": "artēs",
        "gen": "artium",
        "dat": "artibus",
        "acc": "artēs",
        "abl": "artibus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/a/ar/ars.jsonl"
  },
  "ch27-dolor": {
    "forms": {
      "sg": {
        "nom": "dolor",
        "gen": "dolōris",
        "dat": "dolōrī",
        "acc": "dolōrem",
        "abl": "dolōre"
      },
      "pl": {
        "nom": "dolōrēs",
        "gen": "dolōrum",
        "dat": "dolōribus",
        "acc": "dolōrēs",
        "abl": "dolōribus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/d/do/dolor.jsonl"
  },
  "ch27-liber": {
    "forms": {
      "sg": {
        "nom": "liber",
        "gen": "librī",
        "dat": "librō",
        "acc": "librum",
        "abl": "librō"
      },
      "pl": {
        "nom": "librī",
        "gen": "librōrum",
        "dat": "librīs",
        "acc": "librōs",
        "abl": "librīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/l/li/liber.jsonl"
  },
  "ch27-metus": {
    "forms": {
      "sg": {
        "nom": "metus",
        "gen": "metūs",
        "dat": "metuī",
        "acc": "metum",
        "abl": "metū"
      },
      "pl": {
        "nom": "metūs",
        "gen": "metuum",
        "dat": "metibus",
        "acc": "metūs",
        "abl": "metibus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/m/me/metus.jsonl"
  },
  "ch27-pectus": {
    "forms": {
      "sg": {
        "nom": "pectus",
        "gen": "pectoris",
        "dat": "pectorī",
        "acc": "pectus",
        "abl": "pectore"
      },
      "pl": {
        "nom": "pectora",
        "gen": "pectorum",
        "dat": "pectoribus",
        "acc": "pectora",
        "abl": "pectoribus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/p/pe/pectus.jsonl"
  },
  "ch27-tempestās": {
    "forms": {
      "sg": {
        "nom": "tempestās",
        "gen": "tempestātis",
        "dat": "tempestātī",
        "acc": "tempestātem",
        "abl": "tempestāte"
      },
      "pl": {
        "nom": "tempestātēs",
        "gen": "tempestātum",
        "dat": "tempestātibus",
        "acc": "tempestātēs",
        "abl": "tempestātibus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/t/te/tempestas.jsonl"
  },
  "ch27-vīs": {
    "forms": {
      "sg": {
        "nom": "vīs",
        "gen": "vīs",
        "dat": "vī",
        "acc": "vim",
        "abl": "vī"
      },
      "pl": {
        "nom": "vīrēs",
        "gen": "vīrium",
        "dat": "vīribus",
        "acc": "vīrēs",
        "abl": "vīribus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/v/vi/vis.jsonl",
    "review": "marked irregular in the vocab data"
  },
  "ch28-ager": {
    "forms": {
      "sg": {
        "nom": "ager",
        "gen": "agrī",
        "dat": "agrō",
        "acc": "agrum",
        "abl": "agrō"
      },
      "pl": {
        "nom": "agrī",
        "gen": "agrōrum",
        "dat": "agrīs",
        "acc": "agrōs",
        "abl": "agrīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/a/ag/ager.jsonl"
  },
  "ch28-scelus": {
    "forms": {
      "sg": {
        "nom": "scelus",
        "gen": "sceleris",
        "dat": "scelerī",
        "acc": "scelus",
        "abl": "scelere"
      },
      "pl": {
        "nom": "scelera",
        "gen": "scelerum",
        "dat": "sceleribus",
        "acc": "scelera",
        "abl": "sceleribus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/s/sc/scelus.jsonl"
  },
  "ch28-terra": {
    "forms": {
      "sg": {
        "nom": "terra",
        "gen": "terrae",
        "dat": "terrae",
        "acc": "terram",
        "abl": "terrā"
      },
      "pl": {
        "nom": "terrae",
        "gen": "terrārum",
        "dat": "terrīs",
        "acc": "terrās",
        "abl": "terrīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/t/te/terra.jsonl"
  },
  "ch28-virgō": {
    "forms": {
      "sg": {
        "nom": "virgō",
        "gen": "virginis",
        "dat": "virginī",
        "acc": "virginem",
        "abl": "virgine"
      },
      "pl": {
        "nom": "virginēs",
        "gen": "virginum",
        "dat": "virginibus",
        "acc": "virginēs",
        "abl": "virginibus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/v/vi/virgo.jsonl"
  },
  "ch29-gēns": {
    "forms": {
      "sg": {
        "nom": "gēns",
        "gen": "gentis",
        "dat": "gentī",
        "acc": "gentem",
        "abl": "gente"
      },
      "pl": {
        "nom": "gentēs",
        "gen": "gentium",
        "dat": "gentibus",
        "acc": "gentēs",
        "abl": "gentibus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/g/ge/gens.jsonl"
  },
  "ch29-honor": {
    "forms": {
      "sg": {
        "nom": "honor",
        "gen": "honōris",
        "dat": "honōrī",
        "acc": "honōrem",
        "abl": "honōre"
      },
      "pl": {
        "nom": "honōrēs",
        "gen": "honōrum",
        "dat": "honōribus",
        "acc": "honōrēs",
        "abl": "honōribus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/h/ho/honor.jsonl"
  },
  "ch29-ingenium": {
    "forms": {
      "sg": {
        "nom": "ingenium",
        "gen": "ingeniī",
        "dat": "ingeniō",
        "acc": "ingenium",
        "abl": "ingeniō"
      },
      "pl": {
        "nom": "ingenia",
        "gen": "ingeniōrum",
        "dat": "ingeniīs",
        "acc": "ingenia",
        "abl": "ingeniīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/i/in/ingenium.jsonl"
  },
  "ch29-orbis": {
    "forms": {
      "sg": {
        "nom": "orbis",
        "gen": "orbis",
        "dat": "orbī",
        "acc": "orbem",
        "abl": "orbe"
      },
      "pl": {
        "nom": "orbēs",
        "gen": "orbium",
        "dat": "orbibus",
        "acc": "orbēs",
        "abl": "orbibus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/o/or/orbis.jsonl"
  },
  "ch29-somnus": {
    "forms": {
      "sg": {
        "nom": "somnus",
        "gen": "somnī",
        "dat": "somnō",
        "acc": "somnum",
        "abl": "somnō"
      },
      "pl": {
        "nom": "somnī",
        "gen": "somnōrum",
        "dat": "somnīs",
        "acc": "somnōs",
        "abl": "somnīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/s/so/somnus.jsonl"
  },
  "ch30-āra": {
    "forms": {
      "sg": {
        "nom": "āra",
        "gen": "ārae",
        "dat": "ārae",
        "acc": "āram",
        "abl": "ārā"
      },
      "pl": {
        "nom": "ārae",
        "gen": "ārārum",
        "dat": "ārīs",
        "acc": "ārās",
        "abl": "ārīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/a/ar/ara.jsonl"
  },
  "ch30-captīvus": {
    "forms": {
      "sg": {
        "nom": "captīvus",
        "gen": "captīvī",
        "dat": "captīvō",
        "acc": "captīvum",
        "abl": "captīvō"
      },
      "pl": {
        "nom": "captīvī",
        "gen": "captīvōrum",
        "dat": "captīvīs",
        "acc": "captīvōs",
        "abl": "captīvīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/c/ca/captivus.jsonl"
  },
  "ch30-coma": {
    "forms": {
      "sg": {
        "nom": "coma",
        "gen": "comae",
        "dat": "comae",
        "acc": "comam",
        "abl": "comā"
      },
      "pl": {
        "nom": "comae",
        "gen": "comārum",
        "dat": "comīs",
        "acc": "comās",
        "abl": "comīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/c/co/coma.jsonl"
  },
  "ch30-nūmen": {
    "forms": {
      "sg": {
        "nom": "nūmen",
        "gen": "nūminis",
        "dat": "nūminī",
        "acc": "nūmen",
        "abl": "nūmine"
      },
      "pl": {
        "nom": "nūmina",
        "gen": "nūminum",
        "dat": "nūminibus",
        "acc": "nūmina",
        "abl": "nūminibus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/n/nu/numen.jsonl"
  },
  "ch30-ōs": {
    "forms": {
      "sg": {
        "nom": "ōs",
        "gen": "ōris",
        "dat": "ōrī",
        "acc": "ōs",
        "abl": "ōre"
      },
      "pl": {
        "nom": "ōra",
        "gen": "ōrum",
        "dat": "ōribus",
        "acc": "ōra",
        "abl": "ōribus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/o/os/os.jsonl"
  },
  "ch30-virtūs": {
    "forms": {
      "sg": {
        "nom": "virtūs",
        "gen": "virtūtis",
        "dat": "virtūtī",
        "acc": "virtūtem",
        "abl": "virtūte"
      },
      "pl": {
        "nom": "virtūtēs",
        "gen": "virtūtum",
        "dat": "virtūtibus",
        "acc": "virtūtēs",
        "abl": "virtūtibus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/v/vi/virtus.jsonl"
  },
  "ch31-caedēs": {
    "forms": {
      "sg": {
        "nom": "caedēs",
        "gen": "caedis",
        "dat": "caedī",
        "acc": "caedem",
        "abl": "caede"
      },
      "pl": {
        "nom": "caedēs",
        "gen": "caedium",
        "dat": "caedibus",
        "acc": "caedēs",
        "abl": "caedibus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/c/ca/caedes.jsonl"
  },
  "ch31-cāsus": {
    "forms": {
      "sg": {
        "nom": "cāsus",
        "gen": "cāsūs",
        "dat": "cāsuī",
        "acc": "cāsum",
        "abl": "cāsū"
      },
      "pl": {
        "nom": "cāsūs",
        "gen": "cāsuum",
        "dat": "cāsibus",
        "acc": "cāsūs",
        "abl": "cāsibus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/c/ca/casus.jsonl"
  },
  "ch31-causa": {
    "forms": {
      "sg": {
        "nom": "causa",
        "gen": "causae",
        "dat": "causae",
        "acc": "causam",
        "abl": "causā"
      },
      "pl": {
        "nom": "causae",
        "gen": "causārum",
        "dat": "causīs",
        "acc": "causās",
        "abl": "causīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/c/ca/causa.jsonl"
  },
  "ch31-cōnsul": {
    "forms": {
      "sg": {
        "nom": "cōnsul",
        "gen": "cōnsulis",
        "dat": "cōnsulī",
        "acc": "cōnsulem",
        "abl": "cōnsule"
      },
      "pl": {
        "nom": "cōnsulēs",
        "gen": "cōnsulum",
        "dat": "cōnsulibus",
        "acc": "cōnsulēs",
        "abl": "cōnsulibus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/c/co/consul.jsonl"
  },
  "ch31-impetus": {
    "forms": {
      "sg": {
        "nom": "impetus",
        "gen": "impetūs",
        "dat": "impetuī",
        "acc": "impetum",
        "abl": "impetū"
      },
      "pl": {
        "nom": "impetūs",
        "gen": "impetuum",
        "dat": "impetibus",
        "acc": "impetūs",
        "abl": "impetibus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/i/im/impetus.jsonl"
  },
  "ch31-inimīcus": {
    "forms": {
      "sg": {
        "nom": "inimīcus",
        "gen": "inimīcī",
        "dat": "inimīcō",
        "acc": "inimīcum",
        "abl": "inimīcō"
      },
      "pl": {
        "nom": "inimīcī",
        "gen": "inimīcōrum",
        "dat": "inimīcīs",
        "acc": "inimīcōs",
        "abl": "inimīcīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/i/in/inimicus.jsonl"
  },
  "ch31-lītus": {
    "forms": {
      "sg": {
        "nom": "lītus",
        "gen": "lītoris",
        "dat": "lītorī",
        "acc": "lītus",
        "abl": "lītore"
      },
      "pl": {
        "nom": "lītora",
        "gen": "lītorum",
        "dat": "lītoribus",
        "acc": "lītora",
        "abl": "lītoribus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/l/li/litus.jsonl"
  },
  "ch31-mēns": {
    "forms": {
      "sg": {
        "nom": "mēns",
        "gen": "mentis",
        "dat": "mentī",
        "acc": "mentem",
        "abl": "mente"
      },
      "pl": {
        "nom": "mentēs",
        "gen": "mentium",
        "dat": "mentibus",
        "acc": "mentēs",
        "abl": "mentibus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/m/me/mens.jsonl"
  },
  "ch31-numerus": {
    "forms": {
      "sg": {
        "nom": "numerus",
        "gen": "numerī",
        "dat": "numerō",
        "acc": "numerum",
        "abl": "numerō"
      },
      "pl": {
        "nom": "numerī",
        "gen": "numerōrum",
        "dat": "numerīs",
        "acc": "numerōs",
        "abl": "numerīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/n/nu/numerus.jsonl"
  },
  "ch31-patria": {
    "forms": {
      "sg": {
        "nom": "patria",
        "gen": "patriae",
        "dat": "patriae",
        "acc": "patriam",
        "abl": "patriā"
      },
      "pl": {
        "nom": "patriae",
        "gen": "patriārum",
        "dat": "patriīs",
        "acc": "patriās",
        "abl": "patriīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/p/pa/patria.jsonl"
  },
  "ch31-proelium": {
    "forms": {
      "sg": {
        "nom": "proelium",
        "gen": "proeliī",
        "dat": "proeliō",
        "acc": "proelium",
        "abl": "proeliō"
      },
      "pl": {
        "nom": "proelia",
        "gen": "proeliōrum",
        "dat": "proeliīs",
        "acc": "proelia",
        "abl": "proeliīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/p/pr/proelium.jsonl"
  },
  "ch31-rēgnum": {
    "forms": {
      "sg": {
        "nom": "rēgnum",
        "gen": "rēgnī",
        "dat": "rēgnō",
        "acc": "rēgnum",
        "abl": "rēgnō"
      },
      "pl": {
        "nom": "rēgna",
        "gen": "rēgnōrum",
        "dat": "rēgnīs",
        "acc": "rēgna",
        "abl": "rēgnīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/r/re/regnum.jsonl"
  },
  "ch31-victor": {
    "forms": {
      "sg": {
        "nom": "victor",
        "gen": "victōris",
        "dat": "victōrī",
        "acc": "victōrem",
        "abl": "victōre"
      },
      "pl": {
        "nom": "victōrēs",
        "gen": "victōrum",
        "dat": "victōribus",
        "acc": "victōrēs",
        "abl": "victōribus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/v/vi/victor.jsonl"
  },
  "ch32-auxilium": {
    "forms": {
      "sg": {
        "nom": "auxilium",
        "gen": "auxiliī",
        "dat": "auxiliō",
        "acc": "auxilium",
        "abl": "auxiliō"
      },
      "pl": {
        "nom": "auxilia",
        "gen": "auxiliōrum",
        "dat": "auxiliīs",
        "acc": "auxilia",
        "abl": "auxiliīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/a/au/auxilium.jsonl"
  },
  "ch32-fīnis": {
    "forms": {
      "sg": {
        "nom": "fīnis",
        "gen": "fīnis",
        "dat": "fīnī",
        "acc": "fīnem",
        "abl": "fīne"
      },
      "pl": {
        "nom": "fīnēs",
        "gen": "fīnium",
        "dat": "fīnibus",
        "acc": "fīnēs",
        "abl": "fīnibus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/f/fi/finis.jsonl"
  },
  "ch32-flamma": {
    "forms": {
      "sg": {
        "nom": "flamma",
        "gen": "flammae",
        "dat": "flammae",
        "acc": "flammam",
        "abl": "flammā"
      },
      "pl": {
        "nom": "flammae",
        "gen": "flammārum",
        "dat": "flammīs",
        "acc": "flammās",
        "abl": "flammīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/f/fl/flamma.jsonl"
  },
  "ch32-fortūna": {
    "forms": {
      "sg": {
        "nom": "fortūna",
        "gen": "fortūnae",
        "dat": "fortūnae",
        "acc": "fortūnam",
        "abl": "fortūnā"
      },
      "pl": {
        "nom": "fortūnae",
        "gen": "fortūnārum",
        "dat": "fortūnīs",
        "acc": "fortūnās",
        "abl": "fortūnīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/f/fo/fortuna.jsonl"
  },
  "ch32-mōs": {
    "forms": {
      "sg": {
        "nom": "mōs",
        "gen": "mōris",
        "dat": "mōrī",
        "acc": "mōrem",
        "abl": "mōre"
      },
      "pl": {
        "nom": "mōrēs",
        "gen": "mōrum",
        "dat": "mōribus",
        "acc": "mōrēs",
        "abl": "mōribus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/m/mo/mos.jsonl"
  },
  "ch32-populus": {
    "forms": {
      "sg": {
        "nom": "populus",
        "gen": "populī",
        "dat": "populō",
        "acc": "populum",
        "abl": "populō"
      },
      "pl": {
        "nom": "populī",
        "gen": "populōrum",
        "dat": "populīs",
        "acc": "populōs",
        "abl": "populīs"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/p/po/populus.jsonl"
  },
  "ch32-senātus": {
    "forms": {
      "sg": {
        "nom": "senātus",
        "gen": "senātūs",
        "dat": "senātuī",
        "acc": "senātum",
        "abl": "senātū"
      },
      "pl": {
        "nom": "senātūs",
        "gen": "senātuum",
        "dat": "senātibus",
        "acc": "senātūs",
        "abl": "senātibus"
      }
    },
    "source": "https://kaikki.org/dictionary/Latin/meaning/s/se/senatus.jsonl"
  }
};
